#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : portmidi
Version  : 2.0.3
Release  : 2
URL      : https://github.com/PortMidi/portmidi/archive/refs/tags/v2.0.3.tar.gz
Source0  : https://github.com/PortMidi/portmidi/archive/refs/tags/v2.0.3.tar.gz
Summary  : @CMAKE_PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : MIT
Requires: portmidi-lib = %{version}-%{release}
Requires: portmidi-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : glibc-dev

%description
Roger B. Dannenberg
Documentation for PortMidi is found in pm_common/portmidi.h.
Documentation in HTML is available at portmidi.github.io/portmidi_docs/

%package dev
Summary: dev components for the portmidi package.
Group: Development
Requires: portmidi-lib = %{version}-%{release}
Provides: portmidi-devel = %{version}-%{release}
Requires: portmidi = %{version}-%{release}

%description dev
dev components for the portmidi package.


%package lib
Summary: lib components for the portmidi package.
Group: Libraries
Requires: portmidi-license = %{version}-%{release}

%description lib
lib components for the portmidi package.


%package license
Summary: license components for the portmidi package.
Group: Default

%description license
license components for the portmidi package.


%prep
%setup -q -n portmidi-2.0.3
cd %{_builddir}/portmidi-2.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648663779
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1648663779
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/portmidi
cp %{_builddir}/portmidi-2.0.3/license.txt %{buildroot}/usr/share/package-licenses/portmidi/50a53a89a8310af162c249cebfae96e4c42d5dcd
cp %{_builddir}/portmidi-2.0.3/pm_java/pmdefaults/pmdefaults-license.txt %{buildroot}/usr/share/package-licenses/portmidi/c201b1c59f24fb7c5ede7ffb2fd87ab6337ec573
pushd clr-build
%make_install
popd
## install_append content
ln -s libportmidi.so %{buildroot}/usr/lib64/libporttime.so
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pmutil.h
/usr/include/portmidi.h
/usr/include/porttime.h
/usr/lib64/cmake/PortMidi/PortMidiConfig.cmake
/usr/lib64/cmake/PortMidi/PortMidiConfigVersion.cmake
/usr/lib64/cmake/PortMidi/PortMidiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/PortMidi/PortMidiTargets.cmake
/usr/lib64/libportmidi.so
/usr/lib64/libporttime.so
/usr/lib64/pkgconfig/portmidi.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libportmidi.so.2
/usr/lib64/libportmidi.so.2.0.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/portmidi/50a53a89a8310af162c249cebfae96e4c42d5dcd
/usr/share/package-licenses/portmidi/c201b1c59f24fb7c5ede7ffb2fd87ab6337ec573
